name: tether_app
description: "Tether: portapapeles y transferencia de archivos entre tus dispositivos."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  desktop_drop: ^0.7.1
  dio: ^5.7.0
  file_selector: ^1.0.3
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.2
  google_fonts: ^8.2.1
  mime: ^2.0.0
  path: ^1.9.0
  path_provider: ^2.1.5
  socket_io_client: ^2.0.3+1
  super_clipboard: ^0.8.9
  window_manager: ^0.4.3
  tray_manager: ^0.5.3
  shadcn_flutter: ^0.0.53
  flutter_file_dialog: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tray_icon.png
    - assets/logo.png
